export const initialCategories = [
  {
    id: 1,
    hierarchyId: 1,
    name: 'Men',
    slug: 'men',
    level: 1,
    subcategories: [],
  },
  {
    id: 2,
    hierarchyId: 2,
    name: 'Women',
    slug: 'women',
    level: 1,
    subcategories: [],
  },
  {
    id: 3,
    hierarchyId: 3,
    name: 'Kids',
    slug: 'kids',
    level: 1,
    subcategories: [],
  },
  {
    id: 4,
    hierarchyId: 4,
    name: 'Sports',
    slug: 'sports',
    level: 1,
    subcategories: [],
  },
  {
    id: 5,
    hierarchyId: 5,
    name: 'Groomity',
    slug: 'groomity',
    level: 1,
    subcategories: [],
  },
];
