export const initialBanner = [
  {
    id: 1,
    title: 'Flash Sale',
    image: '/images/banner/flash-sale.jpg',
    link: '/c',
    active: true,
    createdAt: '2026-03-24T12:00:00.000Z',
    categories: ['women', 'men', 'kids'],
    isSale: true,
    discount: '2',
  },
  {
    id: 2,
    title: 'Women New Arrivals',
    image: '/images/banner/women-new.jpg',
    link: '/c/women?tag=new-arrivals',
    active: true,
    createdAt: '2026-03-10T09:00:00.000Z',
    isSale: false,
    categories: ['women'],
  },
  {
    id: 3,
    title: 'Men Casual Collection',
    image: '/images/banner/men-casual.jpg',
    link: '/c/men',
    active: true,
    createdAt: '2026-03-15T09:00:00.000Z',
    isSale: false,
    categories: ['men'],
  },
  {
    id: 4,
    title: 'Kids Fun Collection',
    image: '/images/banner/kids-fun.jpg',
    link: '/c/kids',
    active: true,
    createdAt: '2026-03-12T10:00:00.000Z',
    isSale: false,
    categories: ['kids'],
  },
  {
    id: 5,
    title: 'Join Now – 50k OFF for New Users',
    image: '/images/banner/register.jpg',
    link: '/register?code=NEWKLAMBIE50',
    active: true,
    createdAt: '2026-03-12T10:00:00.000Z',
    categories: ['kids', 'men', 'women', 'groomity', 'sports'],
    isSale: false,
    promoCode: 'NEWKLAMBIE50',
  },
];
