export const initialBrands = [
  {
    id: 1,
    name: 'Uniqlo',
    slug: 'uniqlo',
    image: 'uniqlo,jpg',
    description:
      'Timeless everyday wear designed for comfort, quality, and simplicity—blending modern innovation with effortless style.',
    createdAt: '2026-04-14T10:01:43.088Z',
    priority: true,
  },
  {
    id: 2,
    name: 'Suko',
    slug: 'suko',
    image: 'suko.jpg',
    description:
      'Modern, versatile essentials crafted for comfort and everyday style, combining clean design with a contemporary edge.',
    createdAt: '2026-04-14T10:01:43.088Z',
    priority: true,
  },
  {
    id: 3,
    name: 'Adidas',
    slug: 'adidas',
    image: 'adidas.jpg',
    description:
      'Sport-inspired performance wear and street-ready style, blending innovation, comfort, and iconic design.',
    createdAt: '2026-04-14T10:01:43.088Z',
    priority: true,
  },
  {
    id: 4,
    name: 'Nike',
    slug: 'nike',
    image: 'nike.jpg',
    description:
      'Performance-driven sportswear and footwear designed for innovation, comfort, and bold, iconic style.',
    createdAt: '2026-04-14T10:01:43.088Z',
    priority: true,
  },
  {
    id: 5,
    name: 'Zara',
    slug: 'zara',
    image: 'zara.jpg',
    description:
      'Trend-forward fashion with modern designs, offering stylish, versatile pieces for everyday wear.',
    createdAt: '2026-04-14T10:01:43.088Z',
    priority: true,
  },
  {
    id: 6,
    name: 'H&M',
    slug: 'handm',
    image: 'handm.jpg',
    description:
      'Contemporary, affordable fashion combining the latest trends with versatile, stylish pieces for everyday wear.',
    createdAt: '2026-04-14T10:01:43.088Z',
    priority: true,
  },
  {
    id: 7,
    name: 'Skechers',
    slug: 'skechers',
    image: 'skechers.jpg',
    description:
      'Casual and performance footwear designed for all-day comfort, style, and durability, suitable for every lifestyle.',
    createdAt: '2026-04-14T10:01:43.088Z',
    priority: true,
  },
  {
    id: 8,
    name: 'Nevada',
    slug: 'nevada',
    createdAt: '2026-04-14T10:01:43.088Z',
    priority: false,
  },
  {
    id: 9,
    name: 'Cardinal',
    slug: 'cardinal',
    createdAt: '2026-04-14T10:01:43.088Z',
    priority: false,
  },
  {
    id: 10,
    name: 'Puma',
    slug: 'puma',
    createdAt: '2026-04-14T10:01:43.088Z',
    priority: false,
  },
  {
    id: 11,
    name: 'Vans',
    slug: 'vans',
    image: 'vans.jpg',
    description:
      'Iconic skate-inspired footwear and apparel combining casual style, durability, and youthful, creative energy.',
    createdAt: '2026-04-14T10:01:43.088Z',
    priority: true,
  },
  {
    id: 12,
    name: 'Fila',
    slug: 'fila',
    createdAt: '2026-04-14T10:01:43.088Z',
    priority: false,
  },
  {
    id: 13,
    name: 'Nineteen',
    slug: 'nineteen',
    createdAt: '2026-04-14T10:01:43.088Z',
    priority: false,
  },
  {
    id: 14,
    name: 'Police Denim',
    slug: 'police-denim',
    createdAt: '2026-04-14T10:01:43.088Z',
    priority: false,
  },
  {
    id: 15,
    name: 'Cole',
    slug: 'cole',
    createdAt: '2026-04-14T10:01:43.088Z',
    priority: false,
  },
  {
    id: 16,
    name: 'Converse',
    slug: 'converse',
    image: 'converse.jpg',
    description:
      'The brand represents self-expression, creativity, and a casual, street-inspired aesthetic.',
    createdAt: '2026-04-14T10:01:43.088Z',
    priority: true,
  },
  {
    id: 17,
    name: 'Klambie',
    slug: 'klambie',
    image: 'klambie.icon',
    description:
      'Klambie blends handpicked products from established brands with our own original collections.',
    createdAt: '2026-04-14T17:25:32.351Z',
    priority: true,
  },
];
