import { ICategories } from '@/views/pages/c/types';

// Example: slug can be a kebab-case version of the name
export const initialCategories: ICategories[] = [
  {
    id: 1,
    name: 'Men',
    slug: 'men',
    level: 1,
    subcategories: [
      {
        id: 6,
        name: 'Clothing',
        slug: 'clothing',
        level: 2,
        subcategories: [
          {
            id: 9,
            name: 'Outwears',
            slug: 'outwears',
            level: 3,
            subcategories: [
              {
                id: 10,
                name: 'Parkas',
                slug: 'parkas',
                level: 4,
                subcategories: [],
              },
              {
                id: 11,
                name: 'Jackets',
                slug: 'jackets',
                level: 4,
                subcategories: [],
              },
              {
                id: 12,
                name: 'Coats',
                slug: 'coats',
                level: 4,
                subcategories: [],
              },
              {
                id: 22,
                name: 'Flannels',
                slug: 'flannels',
                level: 4,
                subcategories: [],
              },
            ],
          },
          {
            id: 7,
            name: 'T-Shirts',
            slug: 't-shirts',
            level: 3,
            subcategories: [
              {
                id: 8,
                name: 'Oversized',
                slug: 'oversized',
                level: 4,
                subcategories: [],
              },
            ],
          },
          {
            id: 18,
            name: 'Pants',
            slug: 'pants',
            level: 3,
            subcategories: [
              {
                id: 19,
                name: 'Cargos',
                slug: 'cargos',
                level: 4,
                subcategories: [],
              },
              {
                id: 20,
                name: 'Chinos',
                slug: 'chinos',
                level: 4,
                subcategories: [],
              },
              {
                id: 21,
                name: 'Formal',
                slug: 'formal',
                level: 4,
                subcategories: [],
              },
            ],
          },
        ],
      },
      {
        id: 23,
        name: 'Shoes',
        slug: 'shoes',
        level: 2,
        subcategories: [
          {
            id: 29,
            name: 'Sneakers',
            slug: 'sneakers',
            level: 3,
            subcategories: [],
          },
          {
            id: 21,
            name: 'Formal',
            slug: 'formal',
            level: 3,
            subcategories: [],
          },
          {
            id: 30,
            name: 'Slip-Ons',
            slug: 'slip-ons',
            level: 3,
            subcategories: [],
          },
          {
            id: 31,
            name: 'Boots',
            slug: 'boots',
            level: 3,
            subcategories: [],
          },
          {
            id: 32,
            name: 'Sandals',
            slug: 'sandals',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 24,
        name: 'Accessories',
        slug: 'accessories',
        level: 2,
        subcategories: [
          {
            id: 26,
            name: 'Watches',
            slug: 'watches',
            level: 3,
            subcategories: [],
          },
          {
            id: 27,
            name: 'Eyewear',
            slug: 'eyewear',
            level: 3,
            subcategories: [],
          },
          {
            id: 28,
            name: 'Jewellery',
            slug: 'jewellery',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 25,
        name: 'Bags',
        slug: 'bags',
        level: 2,
        subcategories: [
          {
            id: 37,
            name: 'Backpacks',
            slug: 'backpacks',
            level: 3,
            subcategories: [],
          },
          {
            id: 38,
            name: 'Travel Bags',
            slug: 'travel-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 39,
            name: 'Tote Bags',
            slug: 'tote-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 40,
            name: 'Laptop Bags',
            slug: 'laptop-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 41,
            name: 'Crossbody Bags',
            slug: 'crossbody-bags',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 4,
        name: 'Sports',
        slug: 'sports',
        level: 2,
        subcategories: [
          {
            id: 6,
            name: 'Clothing',
            slug: 'clothing',
            level: 3,
            subcategories: [],
          },
          {
            id: 23,
            name: 'Shoes',
            slug: 'shoes',
            level: 3,
            subcategories: [],
          },
          {
            id: 24,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: 'Women',
    slug: 'women',
    level: 1,
    subcategories: [
      {
        id: 6,
        name: 'Clothing',
        slug: 'clothing',
        level: 2,
        subcategories: [
          {
            id: 7,
            name: 'T-Shirts',
            slug: 't-shirts',
            level: 3,
            subcategories: [
              {
                id: 8,
                name: 'Oversized',
                slug: 'oversized',
                level: 4,
                subcategories: [],
              },
            ],
          },
          {
            id: 15,
            name: 'Tops',
            slug: 'tops',
            level: 3,
            subcategories: [
              {
                id: 7,
                name: 'T-Shirts',
                slug: 't-shirts',
                level: 4,
                subcategories: [],
              },
            ],
          },
        ],
      },
      {
        id: 23,
        name: 'Shoes',
        slug: 'shoes',
        level: 2,
        subcategories: [
          {
            id: 29,
            name: 'Sneakers',
            slug: 'sneakers',
            level: 3,
            subcategories: [],
          },
          {
            id: 21,
            name: 'Formal',
            slug: 'formal',
            level: 3,
            subcategories: [],
          },
          {
            id: 30,
            name: 'Slip-Ons',
            slug: 'slip-ons',
            level: 3,
            subcategories: [],
          },
          {
            id: 31,
            name: 'Boots',
            slug: 'boots',
            level: 3,
            subcategories: [],
          },
          {
            id: 32,
            name: 'Sandals',
            slug: 'sandals',
            level: 3,
            subcategories: [],
          },
          {
            id: 33,
            name: 'Heels',
            slug: 'heels',
            level: 3,
            subcategories: [],
          },
          {
            id: 34,
            name: 'Wedges',
            slug: 'wedges',
            level: 3,
            subcategories: [],
          },
          {
            id: 35,
            name: 'Flats',
            slug: 'flats',
            level: 3,
            subcategories: [],
          },
          {
            id: 36,
            name: 'Flip Flops',
            slug: 'flip-flops',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 24,
        name: 'Accessories',
        slug: 'accessories',
        level: 2,
        subcategories: [
          {
            id: 26,
            name: 'Watches',
            slug: 'watches',
            level: 3,
            subcategories: [],
          },
          {
            id: 27,
            name: 'Eyewear',
            slug: 'eyewear',
            level: 3,
            subcategories: [],
          },
          {
            id: 28,
            name: 'Jewellery',
            slug: 'jewellery',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 25,
        name: 'Bags',
        slug: 'bags',
        level: 2,
        subcategories: [
          {
            id: 37,
            name: 'Backpacks',
            slug: 'backpacks',
            level: 3,
            subcategories: [],
          },
          {
            id: 38,
            name: 'Travel Bags',
            slug: 'travel-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 39,
            name: 'Tote Bags',
            slug: 'tote-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 40,
            name: 'Laptop Bags',
            slug: 'laptop-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 41,
            name: 'Crossbody Bags',
            slug: 'crossbody-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 42,
            name: 'Handbags',
            slug: 'handbags',
            level: 3,
            subcategories: [],
          },
          {
            id: 43,
            name: 'Clutch Bags',
            slug: 'clutch-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 44,
            name: 'Leather Bags',
            slug: 'leather-bags',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 4,
        name: 'Sports',
        slug: 'sports',
        level: 2,
        subcategories: [
          {
            id: 6,
            name: 'Clothing',
            slug: 'clothing',
            level: 3,
            subcategories: [],
          },
          {
            id: 23,
            name: 'Shoes',
            slug: 'shoes',
            level: 3,
            subcategories: [],
          },
          {
            id: 24,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
    ],
  },
  {
    id: 3,
    name: 'Kids',
    slug: 'kids',
    level: 1,
    subcategories: [
      {
        id: 46,
        name: 'Girls',
        slug: 'girls',
        level: 2,
        subcategories: [],
      },
      {
        id: 47,
        name: 'Boys',
        slug: 'boys',
        level: 2,
        subcategories: [],
      },
      {
        id: 48,
        name: 'Baby',
        slug: 'baby',
        level: 2,
        subcategories: [],
      },
      {
        id: 6,
        name: 'Clothing',
        slug: 'clothing',
        level: 2,
        subcategories: [
          {
            id: 15,
            name: 'Tops',
            slug: 'tops',
            level: 3,
            subcategories: [],
          },
          {
            id: 49,
            name: 'Shorts',
            slug: 'shorts',
            level: 3,
            subcategories: [],
          },
          {
            id: 50,
            name: 'Underwear',
            slug: 'underwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 51,
            name: 'Skirts',
            slug: 'skirts',
            level: 3,
            subcategories: [],
          },
          {
            id: 52,
            name: 'Costumes',
            slug: 'costumes',
            level: 3,
            subcategories: [],
          },
          {
            id: 53,
            name: 'Clothing Sets',
            slug: 'top-and-bottom-sets',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 23,
        name: 'Shoes',
        slug: 'shoes',
        level: 2,
        subcategories: [
          {
            id: 31,
            name: 'Boots',
            slug: 'boots',
            level: 3,
            subcategories: [],
          },
          {
            id: 29,
            name: 'Sneakers',
            slug: 'sneakers',
            level: 3,
            subcategories: [],
          },
          {
            id: 32,
            name: 'Sandals',
            slug: 'sandals',
            level: 3,
            subcategories: [],
          },
          {
            id: 35,
            name: 'Flats',
            slug: 'flats',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 4,
        name: 'Sports',
        slug: 'sports',
        level: 2,
        subcategories: [
          {
            id: 15,
            name: 'Tops',
            slug: 'tops',
            level: 3,
            subcategories: [],
          },
          {
            id: 54,
            name: 'Bottoms',
            slug: 'bottoms',
            level: 3,
            subcategories: [],
          },
          {
            id: 29,
            name: 'Sneakers',
            slug: 'sneakers',
            level: 3,
            subcategories: [],
          },
          {
            id: 24,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 24,
        name: 'Accessories',
        slug: 'accessories',
        level: 2,
        subcategories: [
          {
            id: 55,
            name: 'Headwear',
            slug: 'headwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 56,
            name: 'Scarves and Gloves',
            slug: 'scarves-and-gloves',
            level: 3,
            subcategories: [],
          },
          {
            id: 57,
            name: 'Belt',
            slug: 'belt',
            level: 3,
            subcategories: [],
          },
          {
            id: 58,
            name: 'Towels',
            slug: 'towels',
            level: 3,
            subcategories: [],
          },
          {
            id: 37,
            name: 'Backpacks',
            slug: 'backpacks',
            level: 3,
            subcategories: [],
          },
          {
            id: 25,
            name: 'Bags',
            slug: 'bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 70,
            name: 'Blankets',
            slug: 'blankets',
            level: 3,
            subcategories: [],
          },
        ],
      },
    ],
  },
  {
    id: 4,
    name: 'Sports',
    slug: 'sports',
    level: 1,
    subcategories: [
      {
        id: 1,
        name: 'Men',
        slug: 'men',
        level: 2,
        subcategories: [
          {
            id: 6,
            name: 'Clothing',
            slug: 'clothing',
            level: 3,
            subcategories: [
              {
                id: 7,
                name: 'T-Shirts',
                slug: 't-shirts',
                level: 4,
                subcategories: [],
              },
              {
                id: 49,
                name: 'Shorts',
                slug: 'shorts',
                level: 4,
                subcategories: [],
              },
              {
                id: 18,
                name: 'Pants',
                slug: 'pants',
                level: 4,
                subcategories: [],
              },
              {
                id: 9,
                name: 'Outwears',
                slug: 'outwears',
                level: 4,
                subcategories: [],
              },
              {
                id: 60,
                name: 'Swimwear',
                slug: 'swimwear',
                level: 4,
                subcategories: [],
              },
              {
                id: 61,
                name: 'Beachwear',
                slug: 'beachwear',
                level: 4,
                subcategories: [],
              },
              {
                id: 62,
                name: 'Tanktops and Singlets',
                slug: 'tanktops-and-singlets',
                level: 4,
                subcategories: [],
              },
              {
                id: 63,
                name: 'Polos',
                slug: 'polos',
                level: 4,
                subcategories: [],
              },
            ],
          },
          {
            id: 59,
            name: 'Footwear',
            slug: 'footwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 24,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 2,
        name: 'Women',
        slug: 'women',
        level: 2,
        subcategories: [
          {
            id: 6,
            name: 'Clothing',
            slug: 'clothing',
            level: 3,
            subcategories: [
              {
                id: 7,
                name: 'T-Shirts',
                slug: 't-shirts',
                level: 4,
                subcategories: [],
              },
              {
                id: 49,
                name: 'Shorts',
                slug: 'shorts',
                level: 4,
                subcategories: [],
              },
              {
                id: 18,
                name: 'Pants',
                slug: 'pants',
                level: 4,
                subcategories: [],
              },
              {
                id: 9,
                name: 'Outwears',
                slug: 'outwears',
                level: 4,
                subcategories: [],
              },
              {
                id: 60,
                name: 'Swimwear',
                slug: 'swimwear',
                level: 4,
                subcategories: [],
              },
              {
                id: 61,
                name: 'Beachwear',
                slug: 'beachwear',
                level: 4,
                subcategories: [],
              },
              {
                id: 62,
                name: 'Tanktops and Singlets',
                slug: 'tanktops-and-singlets',
                level: 4,
                subcategories: [],
              },
            ],
          },
          {
            id: 59,
            name: 'Footwear',
            slug: 'footwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 24,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 3,
        name: 'Kids',
        slug: 'kids',
        level: 2,
        subcategories: [
          {
            id: 29,
            name: 'Sneakers',
            slug: 'sneakers',
            level: 3,
            subcategories: [],
          },
          {
            id: 15,
            name: 'Tops',
            slug: 'tops',
            level: 3,
            subcategories: [],
          },
          {
            id: 54,
            name: 'Bottoms',
            slug: 'bottoms',
            level: 3,
            subcategories: [],
          },
          {
            id: 24,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
    ],
  },
  {
    id: 5,
    name: 'Groomity',
    slug: 'groomity',
    level: 1,
    subcategories: [
      {
        id: 64,
        name: 'Skin Care',
        slug: 'skin-care',
        level: 2,
        subcategories: [],
      },
      {
        id: 65,
        name: 'Make Up',
        slug: 'make-up',
        level: 2,
        subcategories: [],
      },
      {
        id: 66,
        name: 'Hair Care',
        slug: 'hair-care',
        level: 2,
        subcategories: [],
      },
      {
        id: 67,
        name: 'Fragrances',
        slug: 'fragrances',
        level: 2,
        subcategories: [],
      },
      {
        id: 68,
        name: 'Bath and Body',
        slug: 'bath-and-body',
        level: 2,
        subcategories: [],
      },
      {
        id: 69,
        name: "Men's Care",
        slug: 'mens-care',
        level: 2,
        subcategories: [],
      },
      {
        id: 24,
        name: 'Accessories',
        slug: 'accessories',
        level: 2,
        subcategories: [],
      },
    ],
  },
];
