import { ICategories } from '@/views/pages/c/types';

// Example: slug can be a kebab-case version of the name
export const initialCategories: ICategories[] = [
  {
    id: 1,
    name: 'Men',
    slug: 'men',
    level: 1,
    subcategories: [
      {
        id: 69,
        name: "Men's Care",
        slug: 'men-care',
        level: 2,
        subcategories: [
          {
            id: 91,
            name: 'Fragrance',
            slug: 'fragrance',
            level: 3,
            subcategories: [],
          },
          {
            id: 64,
            name: 'Skin Care',
            slug: 'skin-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 66,
            name: 'Hair Care',
            slug: 'hair-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 92,
            name: 'Body Care',
            slug: 'body-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 93,
            name: 'Grooming Tools',
            slug: 'grooming-tools',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 121,
        name: 'Localwears',
        slug: 'localwears',
        level: 2,
        subcategories: [],
      },
      {
        id: 6,
        name: 'Clothing',
        slug: 'clothing',
        level: 2,
        subcategories: [
          {
            id: 78,
            name: 'Shirts',
            slug: 'shirts',
            level: 3,
            subcategories: [],
          },
          {
            id: 72,
            name: 'Etchnic Wear',
            slug: 'etchnic-wear',
            level: 3,
            subcategories: [],
          },
          {
            id: 63,
            name: 'Polos',
            slug: 'polos',
            level: 3,
            subcategories: [],
          },
          {
            id: 74,
            name: 'Jeans',
            slug: 'jeans',
            level: 3,
            subcategories: [],
          },
          {
            id: 49,
            name: 'Shorts',
            slug: 'shorts',
            level: 3,
            subcategories: [],
          },
          {
            id: 50,
            name: 'Underwear',
            slug: 'underwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 61,
            name: 'Beachwear',
            slug: 'beachwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 75,
            name: 'Cardigans',
            slug: 'cardigans',
            level: 3,
            subcategories: [],
          },
          {
            id: 11,
            name: 'Jackets',
            slug: 'jackets',
            level: 3,
            subcategories: [],
          },
          {
            id: 79,
            name: 'Hoodies',
            slug: 'hoodies',
            level: 3,
            subcategories: [],
          },
          {
            id: 80,
            name: 'Blazers and Suits',
            slug: 'blazers-and-suits',
            level: 3,
            subcategories: [],
          },
          {
            id: 81,
            name: 'Socks',
            slug: 'socks',
            level: 3,
            subcategories: [],
          },
          {
            id: 9,
            name: 'Outwears',
            slug: 'outwears',
            level: 3,
            subcategories: [
              {
                id: 10,
                name: 'Parkas',
                slug: 'parkas',
                level: 4,
                subcategories: [],
              },
              {
                id: 11,
                name: 'Jackets',
                slug: 'jackets',
                level: 4,
                subcategories: [],
              },
              {
                id: 12,
                name: 'Coats',
                slug: 'coats',
                level: 4,
                subcategories: [],
              },
              {
                id: 22,
                name: 'Flannels',
                slug: 'flannels',
                level: 4,
                subcategories: [],
              },
            ],
          },
          {
            id: 7,
            name: 'T-Shirts',
            slug: 't-shirts',
            level: 3,
            subcategories: [
              {
                id: 8,
                name: 'Oversized',
                slug: 'oversized',
                level: 4,
                subcategories: [],
              },
            ],
          },
          {
            id: 18,
            name: 'Pants',
            slug: 'pants',
            level: 3,
            subcategories: [
              {
                id: 19,
                name: 'Cargos',
                slug: 'cargos',
                level: 4,
                subcategories: [],
              },
              {
                id: 20,
                name: 'Chinos',
                slug: 'chinos',
                level: 4,
                subcategories: [],
              },
              {
                id: 21,
                name: 'Formal',
                slug: 'formal',
                level: 4,
                subcategories: [],
              },
            ],
          },
        ],
      },
      {
        id: 23,
        name: 'Shoes',
        slug: 'shoes',
        level: 2,
        subcategories: [
          {
            id: 82,
            name: 'Sports Shoes',
            slug: 'sports-shoes',
            level: 3,
            subcategories: [],
          },
          {
            id: 83,
            name: 'Shoes Accessories',
            slug: 'shoes-accessories',
            level: 3,
            subcategories: [],
          },
          {
            id: 29,
            name: 'Sneakers',
            slug: 'sneakers',
            level: 3,
            subcategories: [],
          },
          {
            id: 21,
            name: 'Formal',
            slug: 'formal',
            level: 3,
            subcategories: [],
          },
          {
            id: 30,
            name: 'Slip-Ons',
            slug: 'slip-ons',
            level: 3,
            subcategories: [],
          },
          {
            id: 31,
            name: 'Boots',
            slug: 'boots',
            level: 3,
            subcategories: [],
          },
          {
            id: 32,
            name: 'Sandals',
            slug: 'sandals',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 24,
        name: 'Accessories',
        slug: 'accessories',
        level: 2,
        subcategories: [
          {
            id: 84,
            name: 'Belts',
            slug: 'belts',
            level: 3,
            subcategories: [],
          },
          {
            id: 85,
            name: 'Wallets',
            slug: 'wallets',
            level: 3,
            subcategories: [],
          },
          {
            id: 86,
            name: 'Hats and Caps',
            slug: 'hats-and-caps',
            level: 3,
            subcategories: [],
          },
          {
            id: 87,
            name: 'Stationery',
            slug: 'stationery',
            level: 3,
            subcategories: [],
          },
          {
            id: 88,
            name: 'Ties and Accessories',
            slug: 'ties-and-accessories',
            level: 3,
            subcategories: [],
          },
          {
            id: 89,
            name: 'Other Accessories',
            slug: 'other-accessories',
            level: 3,
            subcategories: [],
          },
          {
            id: 90,
            name: 'Scarves and Shawls',
            slug: 'scarves-and-shawls',
            level: 3,
            subcategories: [],
          },
          {
            id: 26,
            name: 'Watches',
            slug: 'watches',
            level: 3,
            subcategories: [],
          },
          {
            id: 27,
            name: 'Eyewear',
            slug: 'eyewear',
            level: 3,
            subcategories: [],
          },
          {
            id: 28,
            name: 'Jewellery',
            slug: 'jewellery',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 25,
        name: 'Bags',
        slug: 'bags',
        level: 2,
        subcategories: [
          {
            id: 37,
            name: 'Backpacks',
            slug: 'backpacks',
            level: 3,
            subcategories: [],
          },
          {
            id: 38,
            name: 'Travel Bags',
            slug: 'travel-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 39,
            name: 'Tote Bags',
            slug: 'tote-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 40,
            name: 'Laptop Bags',
            slug: 'laptop-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 41,
            name: 'Crossbody Bags',
            slug: 'crossbody-bags',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 4,
        name: 'Sports',
        slug: 'sports',
        level: 2,
        subcategories: [
          {
            id: 6,
            name: 'Clothing',
            slug: 'clothing',
            level: 3,
            subcategories: [],
          },
          {
            id: 23,
            name: 'Shoes',
            slug: 'shoes',
            level: 3,
            subcategories: [],
          },
          {
            id: 24,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: 'Women',
    slug: 'women',
    level: 1,
    subcategories: [
      {
        id: 106,
        name: 'Beauty',
        slug: 'beauty',
        level: 2,
        subcategories: [
          {
            id: 64,
            name: 'Skin Care',
            slug: 'skin-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 107,
            name: 'Nail Care',
            slug: 'nail-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 66,
            name: 'Hair Care',
            slug: 'hair-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 91,
            name: 'Fragrance',
            slug: 'fragrance',
            level: 3,
            subcategories: [],
          },
          {
            id: 68,
            name: 'Bath and Body',
            slug: 'bath-and-body',
            level: 3,
            subcategories: [],
          },
          {
            id: 24,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 121,
        name: 'Localwears',
        slug: 'localwears',
        level: 2,
        subcategories: [],
      },
      {
        id: 6,
        name: 'Clothing',
        slug: 'clothing',
        level: 2,
        subcategories: [
          {
            id: 71,
            name: 'Dresses',
            slug: 'dresses',
            level: 3,
            subcategories: [],
          },
          {
            id: 72,
            name: 'Etchnic Wear',
            slug: 'etchnic-wear',
            level: 3,
            subcategories: [],
          },
          {
            id: 51,
            name: 'Skirts',
            slug: 'skirts',
            level: 3,
            subcategories: [],
          },
          {
            id: 49,
            name: 'Shorts',
            slug: 'shorts',
            level: 3,
            subcategories: [],
          },
          {
            id: 14,
            name: 'Blazers',
            slug: 'blazers',
            level: 3,
            subcategories: [],
          },
          {
            id: 73,
            name: 'Lingerie',
            slug: 'lingerie',
            level: 3,
            subcategories: [],
          },
          {
            id: 60,
            name: 'Swimwear',
            slug: 'swimwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 61,
            name: 'Beachwear',
            slug: 'beachwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 74,
            name: 'Jeans',
            slug: 'jeans',
            level: 3,
            subcategories: [],
          },
          {
            id: 18,
            name: 'Pants',
            slug: 'pants',
            level: 3,
            subcategories: [],
          },
          {
            id: 75,
            name: 'Cardigans',
            slug: 'cardigans',
            level: 3,
            subcategories: [],
          },
          {
            id: 11,
            name: 'Jackets',
            slug: 'jackets',
            level: 3,
            subcategories: [],
          },
          {
            id: 76,
            name: 'Maternity',
            slug: 'maternity',
            level: 3,
            subcategories: [],
          },
          {
            id: 77,
            name: 'Playsuits',
            slug: 'playsuits',
            level: 3,
            subcategories: [],
          },
          {
            id: 81,
            name: 'Socks',
            slug: 'socks',
            level: 3,
            subcategories: [],
          },
          {
            id: 7,
            name: 'T-Shirts',
            slug: 't-shirts',
            level: 3,
            subcategories: [
              {
                id: 8,
                name: 'Oversized',
                slug: 'oversized',
                level: 4,
                subcategories: [],
              },
            ],
          },
          {
            id: 15,
            name: 'Tops',
            slug: 'tops',
            level: 3,
            subcategories: [
              {
                id: 7,
                name: 'T-Shirts',
                slug: 't-shirts',
                level: 4,
                subcategories: [],
              },
            ],
          },
        ],
      },
      {
        id: 23,
        name: 'Shoes',
        slug: 'shoes',
        level: 2,
        subcategories: [
          {
            id: 29,
            name: 'Sneakers',
            slug: 'sneakers',
            level: 3,
            subcategories: [],
          },
          {
            id: 21,
            name: 'Formal',
            slug: 'formal',
            level: 3,
            subcategories: [],
          },
          {
            id: 30,
            name: 'Slip-Ons',
            slug: 'slip-ons',
            level: 3,
            subcategories: [],
          },
          {
            id: 31,
            name: 'Boots',
            slug: 'boots',
            level: 3,
            subcategories: [],
          },
          {
            id: 32,
            name: 'Sandals',
            slug: 'sandals',
            level: 3,
            subcategories: [],
          },
          {
            id: 33,
            name: 'Heels',
            slug: 'heels',
            level: 3,
            subcategories: [],
          },
          {
            id: 34,
            name: 'Wedges',
            slug: 'wedges',
            level: 3,
            subcategories: [],
          },
          {
            id: 35,
            name: 'Flats',
            slug: 'flats',
            level: 3,
            subcategories: [],
          },
          {
            id: 36,
            name: 'Flip Flops',
            slug: 'flip-flops',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 24,
        name: 'Accessories',
        slug: 'accessories',
        level: 2,
        subcategories: [
          {
            id: 26,
            name: 'Watches',
            slug: 'watches',
            level: 3,
            subcategories: [],
          },
          {
            id: 27,
            name: 'Eyewear',
            slug: 'eyewear',
            level: 3,
            subcategories: [],
          },
          {
            id: 28,
            name: 'Jewellery',
            slug: 'jewellery',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 25,
        name: 'Bags',
        slug: 'bags',
        level: 2,
        subcategories: [
          {
            id: 37,
            name: 'Backpacks',
            slug: 'backpacks',
            level: 3,
            subcategories: [],
          },
          {
            id: 38,
            name: 'Travel Bags',
            slug: 'travel-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 39,
            name: 'Tote Bags',
            slug: 'tote-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 40,
            name: 'Laptop Bags',
            slug: 'laptop-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 41,
            name: 'Crossbody Bags',
            slug: 'crossbody-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 42,
            name: 'Handbags',
            slug: 'handbags',
            level: 3,
            subcategories: [],
          },
          {
            id: 43,
            name: 'Clutch Bags',
            slug: 'clutch-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 44,
            name: 'Leather Bags',
            slug: 'leather-bags',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 4,
        name: 'Sports',
        slug: 'sports',
        level: 2,
        subcategories: [
          {
            id: 6,
            name: 'Clothing',
            slug: 'clothing',
            level: 3,
            subcategories: [],
          },
          {
            id: 23,
            name: 'Shoes',
            slug: 'shoes',
            level: 3,
            subcategories: [],
          },
          {
            id: 24,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
    ],
  },
  {
    id: 3,
    name: 'Kids',
    slug: 'kids',
    level: 1,
    subcategories: [
      {
        id: 46,
        name: 'Girls',
        slug: 'girls',
        level: 2,
        subcategories: [],
      },
      {
        id: 47,
        name: 'Boys',
        slug: 'boys',
        level: 2,
        subcategories: [],
      },
      {
        id: 48,
        name: 'Baby',
        slug: 'baby',
        level: 2,
        subcategories: [],
      },
      {
        id: 6,
        name: 'Clothing',
        slug: 'clothing',
        level: 2,
        subcategories: [
          {
            id: 15,
            name: 'Tops',
            slug: 'tops',
            level: 3,
            subcategories: [],
          },
          {
            id: 49,
            name: 'Shorts',
            slug: 'shorts',
            level: 3,
            subcategories: [],
          },
          {
            id: 50,
            name: 'Underwear',
            slug: 'underwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 51,
            name: 'Skirts',
            slug: 'skirts',
            level: 3,
            subcategories: [],
          },
          {
            id: 52,
            name: 'Costumes',
            slug: 'costumes',
            level: 3,
            subcategories: [],
          },
          {
            id: 53,
            name: 'Clothing Sets',
            slug: 'top-and-bottom-sets',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 23,
        name: 'Shoes',
        slug: 'shoes',
        level: 2,
        subcategories: [
          {
            id: 31,
            name: 'Boots',
            slug: 'boots',
            level: 3,
            subcategories: [],
          },
          {
            id: 29,
            name: 'Sneakers',
            slug: 'sneakers',
            level: 3,
            subcategories: [],
          },
          {
            id: 32,
            name: 'Sandals',
            slug: 'sandals',
            level: 3,
            subcategories: [],
          },
          {
            id: 35,
            name: 'Flats',
            slug: 'flats',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 4,
        name: 'Sports',
        slug: 'sports',
        level: 2,
        subcategories: [
          {
            id: 15,
            name: 'Tops',
            slug: 'tops',
            level: 3,
            subcategories: [],
          },
          {
            id: 54,
            name: 'Bottoms',
            slug: 'bottoms',
            level: 3,
            subcategories: [],
          },
          {
            id: 29,
            name: 'Sneakers',
            slug: 'sneakers',
            level: 3,
            subcategories: [],
          },
          {
            id: 24,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 24,
        name: 'Accessories',
        slug: 'accessories',
        level: 2,
        subcategories: [
          {
            id: 55,
            name: 'Headwear',
            slug: 'headwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 56,
            name: 'Scarves and Gloves',
            slug: 'scarves-and-gloves',
            level: 3,
            subcategories: [],
          },
          {
            id: 57,
            name: 'Belt',
            slug: 'belt',
            level: 3,
            subcategories: [],
          },
          {
            id: 58,
            name: 'Towels',
            slug: 'towels',
            level: 3,
            subcategories: [],
          },
          {
            id: 37,
            name: 'Backpacks',
            slug: 'backpacks',
            level: 3,
            subcategories: [],
          },
          {
            id: 25,
            name: 'Bags',
            slug: 'bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 70,
            name: 'Blankets',
            slug: 'blankets',
            level: 3,
            subcategories: [],
          },
        ],
      },
    ],
  },
  {
    id: 4,
    name: 'Sports',
    slug: 'sports',
    level: 1,
    subcategories: [
      {
        id: 1,
        name: 'Men',
        slug: 'men',
        level: 2,
        subcategories: [
          {
            id: 6,
            name: 'Clothing',
            slug: 'clothing',
            level: 3,
            subcategories: [
              {
                id: 7,
                name: 'T-Shirts',
                slug: 't-shirts',
                level: 4,
                subcategories: [],
              },
              {
                id: 49,
                name: 'Shorts',
                slug: 'shorts',
                level: 4,
                subcategories: [],
              },
              {
                id: 18,
                name: 'Pants',
                slug: 'pants',
                level: 4,
                subcategories: [],
              },
              {
                id: 9,
                name: 'Outwears',
                slug: 'outwears',
                level: 4,
                subcategories: [],
              },
              {
                id: 60,
                name: 'Swimwear',
                slug: 'swimwear',
                level: 4,
                subcategories: [],
              },
              {
                id: 61,
                name: 'Beachwear',
                slug: 'beachwear',
                level: 4,
                subcategories: [],
              },
              {
                id: 62,
                name: 'Tanktops and Singlets',
                slug: 'tanktops-and-singlets',
                level: 4,
                subcategories: [],
              },
              {
                id: 63,
                name: 'Polos',
                slug: 'polos',
                level: 4,
                subcategories: [],
              },
            ],
          },
          {
            id: 59,
            name: 'Footwear',
            slug: 'footwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 24,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 2,
        name: 'Women',
        slug: 'women',
        level: 2,
        subcategories: [
          {
            id: 6,
            name: 'Clothing',
            slug: 'clothing',
            level: 3,
            subcategories: [
              {
                id: 7,
                name: 'T-Shirts',
                slug: 't-shirts',
                level: 4,
                subcategories: [],
              },
              {
                id: 49,
                name: 'Shorts',
                slug: 'shorts',
                level: 4,
                subcategories: [],
              },
              {
                id: 18,
                name: 'Pants',
                slug: 'pants',
                level: 4,
                subcategories: [],
              },
              {
                id: 9,
                name: 'Outwears',
                slug: 'outwears',
                level: 4,
                subcategories: [],
              },
              {
                id: 60,
                name: 'Swimwear',
                slug: 'swimwear',
                level: 4,
                subcategories: [],
              },
              {
                id: 61,
                name: 'Beachwear',
                slug: 'beachwear',
                level: 4,
                subcategories: [],
              },
              {
                id: 62,
                name: 'Tanktops and Singlets',
                slug: 'tanktops-and-singlets',
                level: 4,
                subcategories: [],
              },
            ],
          },
          {
            id: 59,
            name: 'Footwear',
            slug: 'footwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 24,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 3,
        name: 'Kids',
        slug: 'kids',
        level: 2,
        subcategories: [
          {
            id: 29,
            name: 'Sneakers',
            slug: 'sneakers',
            level: 3,
            subcategories: [],
          },
          {
            id: 15,
            name: 'Tops',
            slug: 'tops',
            level: 3,
            subcategories: [],
          },
          {
            id: 54,
            name: 'Bottoms',
            slug: 'bottoms',
            level: 3,
            subcategories: [],
          },
          {
            id: 24,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
    ],
  },
  {
    id: 5,
    name: 'Groomity',
    slug: 'groomity',
    level: 1,
    subcategories: [
      {
        id: 64,
        name: 'Skin Care',
        slug: 'skin-care',
        level: 2,
        subcategories: [
          {
            id: 94,
            name: 'Masks',
            slug: 'masks',
            level: 3,
            subcategories: [],
          },
          {
            id: 95,
            name: 'Moisturisers',
            slug: 'moisturisers',
            level: 3,
            subcategories: [],
          },
          {
            id: 96,
            name: 'Sun Care',
            slug: 'sun-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 97,
            name: 'Skincare Sets',
            slug: 'skincare-sets',
            level: 3,
            subcategories: [],
          },
          {
            id: 98,
            name: 'Cleansers',
            slug: 'cleansers',
            level: 3,
            subcategories: [],
          },
          {
            id: 99,
            name: 'Toners',
            slug: 'toners',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 65,
        name: 'Make Up',
        slug: 'make-up',
        level: 2,
        subcategories: [
          {
            id: 100,
            name: 'Cheeks',
            slug: 'cheeks',
            level: 3,
            subcategories: [],
          },
          {
            id: 101,
            name: 'Face',
            slug: 'face',
            level: 3,
            subcategories: [],
          },
          {
            id: 102,
            name: 'Lips',
            slug: 'lips',
            level: 3,
            subcategories: [],
          },
          {
            id: 103,
            name: 'Eyes',
            slug: 'eyes',
            level: 3,
            subcategories: [],
          },
          {
            id: 104,
            name: 'Removers',
            slug: 'removers',
            level: 3,
            subcategories: [],
          },
          {
            id: 105,
            name: 'Palettes',
            slug: 'palettes',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 66,
        name: 'Hair Care',
        slug: 'hair-care',
        level: 2,
        subcategories: [
          {
            id: 108,
            name: 'Shampooo and Conditioner',
            slug: 'shampooo-and-conditioner',
            level: 3,
            subcategories: [],
          },
          {
            id: 109,
            name: 'Hair Oils',
            slug: 'hair-oils',
            level: 3,
            subcategories: [],
          },
          {
            id: 110,
            name: 'Hair Tools',
            slug: 'hair-tools',
            level: 3,
            subcategories: [],
          },
          {
            id: 111,
            name: 'Hair Care Sets',
            slug: 'hair-care-sets',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 67,
        name: 'Fragrances',
        slug: 'fragrances',
        level: 2,
        subcategories: [
          {
            id: 112,
            name: 'Women Fragrances',
            slug: 'women-fragrances',
            level: 3,
            subcategories: [],
          },
          {
            id: 113,
            name: 'Men Fragrances',
            slug: 'men-fragrances',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 68,
        name: 'Bath and Body',
        slug: 'bath-and-body',
        level: 2,
        subcategories: [
          {
            id: 114,
            name: 'Personal Care',
            slug: 'personal-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 115,
            name: 'Hand and Body Wash',
            slug: 'hand-and-body-wash',
            level: 3,
            subcategories: [],
          },
          {
            id: 95,
            name: 'Moisturisers',
            slug: 'moisturisers',
            level: 3,
            subcategories: [],
          },
          {
            id: 116,
            name: 'Scrubs and Exfoliants',
            slug: 'scrubs-and-exfoliants',
            level: 3,
            subcategories: [],
          },
          {
            id: 96,
            name: 'Sun Care',
            slug: 'sun-care',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 69,
        name: "Men's Care",
        slug: 'men-care',
        level: 2,
        subcategories: [
          {
            id: 67,
            name: 'Fragrances',
            slug: 'fragrances',
            level: 3,
            subcategories: [],
          },
          {
            id: 64,
            name: 'Skin Care',
            slug: 'skin-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 66,
            name: 'Hair Care',
            slug: 'hair-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 92,
            name: 'Body Care',
            slug: 'body-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 93,
            name: 'Grooming Tools',
            slug: 'grooming-tools',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 24,
        name: 'Accessories',
        slug: 'accessories',
        level: 2,
        subcategories: [
          {
            id: 117,
            name: 'Brushes and Blenders',
            slug: 'brushes-and-blenders',
            level: 3,
            subcategories: [],
          },
          {
            id: 118,
            name: 'Beauty Devices',
            slug: 'beauty-devices',
            level: 3,
            subcategories: [],
          },
          {
            id: 119,
            name: 'Beauty Accessories',
            slug: 'beauty-accessories',
            level: 3,
            subcategories: [],
          },
          {
            id: 120,
            name: 'Make Up Bags',
            slug: 'make-up-bags',
            level: 3,
            subcategories: [],
          },
        ],
      },
    ],
  },
];
