import { ICategories } from '@/views/pages/c/types';

// Example: slug can be a kebab-case version of the name
export const initialCategories: ICategories[] = [
  {
    id: 1,
    hierarchyId: 1,
    name: 'Men',
    slug: 'men',
    level: 1,
    subcategories: [
      {
        id: 4,
        hierarchyId: 10,
        name: 'Sports',
        slug: 'sports',
        level: 2,
        subcategories: [
          {
            id: 6,
            hierarchyId: 114,
            name: 'Clothing',
            slug: 'clothing',
            level: 3,
            subcategories: [],
          },
          {
            id: 7,
            hierarchyId: 115,
            name: 'Shoes',
            slug: 'shoes',
            level: 3,
            subcategories: [],
          },
          {
            id: 8,
            hierarchyId: 116,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 15,
        hierarchyId: 24,
        name: "Men's Care",
        slug: 'men-care',
        level: 2,
        subcategories: [
          {
            id: 93,
            hierarchyId: 117,
            name: 'Fragrance',
            slug: 'fragrance',
            level: 3,
            subcategories: [],
          },
          {
            id: 18,
            hierarchyId: 118,
            name: 'Skin Care',
            slug: 'skin-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 20,
            hierarchyId: 119,
            name: 'Hair Care',
            slug: 'hair-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 41,
            hierarchyId: 120,
            name: 'Body Care',
            slug: 'body-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 42,
            hierarchyId: 121,
            name: 'Grooming Tools',
            slug: 'grooming-tools',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 10,
        hierarchyId: 25,
        name: 'Localwears',
        slug: 'localwears',
        level: 2,
        subcategories: [],
      },
      {
        id: 6,
        hierarchyId: 6,
        name: 'Clothing',
        slug: 'clothing',
        level: 2,
        subcategories: [
          {
            id: 50,
            hierarchyId: 69,
            name: 'Shirts',
            slug: 'shirts',
            level: 3,
            subcategories: [],
          },
          {
            id: 51,
            hierarchyId: 70,
            name: 'Etchnic Wear',
            slug: 'etchnic-wear',
            level: 3,
            subcategories: [],
          },
          {
            id: 52,
            hierarchyId: 71,
            name: 'Polos',
            slug: 'polos',
            level: 3,
            subcategories: [],
          },
          {
            id: 53,
            hierarchyId: 72,
            name: 'Jeans',
            slug: 'jeans',
            level: 3,
            subcategories: [],
          },
          {
            id: 54,
            hierarchyId: 73,
            name: 'Shorts',
            slug: 'shorts',
            level: 3,
            subcategories: [],
          },
          {
            id: 55,
            hierarchyId: 74,
            name: 'Underwear',
            slug: 'underwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 56,
            hierarchyId: 75,
            name: 'Beachwear',
            slug: 'beachwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 57,
            hierarchyId: 76,
            name: 'Cardigans',
            slug: 'cardigans',
            level: 3,
            subcategories: [],
          },
          {
            id: 58,
            hierarchyId: 77,
            name: 'Jackets',
            slug: 'jackets',
            level: 3,
            subcategories: [],
          },
          {
            id: 59,
            hierarchyId: 78,
            name: 'Hoodies',
            slug: 'hoodies',
            level: 3,
            subcategories: [],
          },
          {
            id: 60,
            hierarchyId: 79,
            name: 'Blazers and Suits',
            slug: 'blazers-and-suits',
            level: 3,
            subcategories: [],
          },
          {
            id: 61,
            hierarchyId: 80,
            name: 'Socks',
            slug: 'socks',
            level: 3,
            subcategories: [],
          },
          {
            id: 62,
            hierarchyId: 81,
            name: 'Outwears',
            slug: 'outwears',
            level: 3,
            subcategories: [
              {
                id: 65,
                hierarchyId: 84,
                name: 'Parkas',
                slug: 'parkas',
                level: 4,
                subcategories: [],
              },
              {
                id: 58,
                hierarchyId: 85,
                name: 'Jackets',
                slug: 'jackets',
                level: 4,
                subcategories: [],
              },
              {
                id: 66,
                hierarchyId: 86,
                name: 'Coats',
                slug: 'coats',
                level: 4,
                subcategories: [],
              },
              {
                id: 67,
                hierarchyId: 87,
                name: 'Flannels',
                slug: 'flannels',
                level: 4,
                subcategories: [],
              },
            ],
          },
          {
            id: 63,
            hierarchyId: 82,
            name: 'T-Shirts',
            slug: 't-shirts',
            level: 3,
            subcategories: [
              {
                id: 71,
                hierarchyId: 91,
                name: 'Oversized',
                slug: 'oversized',
                level: 4,
                subcategories: [],
              },
            ],
          },
          {
            id: 64,
            hierarchyId: 83,
            name: 'Pants',
            slug: 'pants',
            level: 3,
            subcategories: [
              {
                id: 68,
                hierarchyId: 88,
                name: 'Cargos',
                slug: 'cargos',
                level: 4,
                subcategories: [],
              },
              {
                id: 69,
                hierarchyId: 89,
                name: 'Chinos',
                slug: 'chinos',
                level: 4,
                subcategories: [],
              },
              {
                id: 70,
                hierarchyId: 90,
                name: 'Formal',
                slug: 'formal',
                level: 4,
                subcategories: [],
              },
            ],
          },
        ],
      },
      {
        id: 7,
        hierarchyId: 7,
        name: 'Shoes',
        slug: 'shoes',
        level: 2,
        subcategories: [
          {
            id: 72,
            hierarchyId: 92,
            name: 'Sports Shoes',
            slug: 'sports-shoes',
            level: 3,
            subcategories: [],
          },
          {
            id: 73,
            hierarchyId: 93,
            name: 'Shoes Accessories',
            slug: 'shoes-accessories',
            level: 3,
            subcategories: [],
          },
          {
            id: 74,
            hierarchyId: 94,
            name: 'Sneakers',
            slug: 'sneakers',
            level: 3,
            subcategories: [],
          },
          {
            id: 70,
            hierarchyId: 95,
            name: 'Formal',
            slug: 'formal',
            level: 3,
            subcategories: [],
          },
          {
            id: 75,
            hierarchyId: 96,
            name: 'Slip-Ons',
            slug: 'slip-ons',
            level: 3,
            subcategories: [],
          },
          {
            id: 76,
            hierarchyId: 97,
            name: 'Boots',
            slug: 'boots',
            level: 3,
            subcategories: [],
          },
          {
            id: 77,
            hierarchyId: 98,
            name: 'Sandals',
            slug: 'sandals',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 8,
        hierarchyId: 8,
        name: 'Accessories',
        slug: 'accessories',
        level: 2,
        subcategories: [
          {
            id: 79,
            hierarchyId: 100,
            name: 'Wallets',
            slug: 'wallets',
            level: 3,
            subcategories: [],
          },
          {
            id: 80,
            hierarchyId: 101,
            name: 'Hats and Caps',
            slug: 'hats-and-caps',
            level: 3,
            subcategories: [],
          },
          {
            id: 81,
            hierarchyId: 102,
            name: 'Stationery',
            slug: 'stationery',
            level: 3,
            subcategories: [],
          },
          {
            id: 82,
            hierarchyId: 103,
            name: 'Ties and Accessories',
            slug: 'ties-and-accessories',
            level: 3,
            subcategories: [],
          },
          {
            id: 83,
            hierarchyId: 104,
            name: 'Other Accessories',
            slug: 'other-accessories',
            level: 3,
            subcategories: [],
          },
          {
            id: 84,
            hierarchyId: 105,
            name: 'Scarves and Shawls',
            slug: 'scarves-and-shawls',
            level: 3,
            subcategories: [],
          },
          {
            id: 85,
            hierarchyId: 106,
            name: 'Watches',
            slug: 'watches',
            level: 3,
            subcategories: [],
          },
          {
            id: 86,
            hierarchyId: 107,
            name: 'Eyewear',
            slug: 'eyewear',
            level: 3,
            subcategories: [],
          },
          {
            id: 87,
            hierarchyId: 108,
            name: 'Jewellery',
            slug: 'jewellery',
            level: 3,
            subcategories: [],
          },
          {
            id: 78,
            hierarchyId: 99,
            name: 'Belts',
            slug: 'belts',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 9,
        hierarchyId: 9,
        name: 'Bags',
        slug: 'bags',
        level: 2,
        subcategories: [
          {
            id: 88,
            hierarchyId: 109,
            name: 'Backpacks',
            slug: 'backpacks',
            level: 3,
            subcategories: [],
          },
          {
            id: 89,
            hierarchyId: 110,
            name: 'Travel Bags',
            slug: 'travel-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 90,
            hierarchyId: 111,
            name: 'Tote Bags',
            slug: 'tote-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 91,
            hierarchyId: 112,
            name: 'Laptop Bags',
            slug: 'laptop-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 92,
            hierarchyId: 113,
            name: 'Crossbody Bags',
            slug: 'crossbody-bags',
            level: 3,
            subcategories: [],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    hierarchyId: 2,
    name: 'Women',
    slug: 'women',
    level: 1,
    subcategories: [
      {
        id: 6,
        hierarchyId: 11,
        name: 'Clothing',
        slug: 'clothing',
        level: 2,
        subcategories: [
          {
            id: 94,
            hierarchyId: 122,
            name: 'Dresses',
            slug: 'dresses',
            level: 3,
            subcategories: [],
          },
          {
            id: 51,
            hierarchyId: 123,
            name: 'Etchnic Wear',
            slug: 'etchnic-wear',
            level: 3,
            subcategories: [],
          },
          {
            id: 95,
            hierarchyId: 124,
            name: 'Skirts',
            slug: 'skirts',
            level: 3,
            subcategories: [],
          },
          {
            id: 54,
            hierarchyId: 125,
            name: 'Shorts',
            slug: 'shorts',
            level: 3,
            subcategories: [],
          },
          {
            id: 96,
            hierarchyId: 126,
            name: 'Blazers',
            slug: 'blazers',
            level: 3,
            subcategories: [],
          },
          {
            id: 97,
            hierarchyId: 127,
            name: 'Lingerie',
            slug: 'lingerie',
            level: 3,
            subcategories: [],
          },
          {
            id: 98,
            hierarchyId: 128,
            name: 'Swimwear',
            slug: 'swimwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 56,
            hierarchyId: 129,
            name: 'Beachwear',
            slug: 'beachwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 53,
            hierarchyId: 130,
            name: 'Jeans',
            slug: 'jeans',
            level: 3,
            subcategories: [],
          },
          {
            id: 64,
            hierarchyId: 131,
            name: 'Pants',
            slug: 'pants',
            level: 3,
            subcategories: [],
          },
          {
            id: 57,
            hierarchyId: 132,
            name: 'Cardigans',
            slug: 'cardigans',
            level: 3,
            subcategories: [],
          },
          {
            id: 58,
            hierarchyId: 133,
            name: 'Jackets',
            slug: 'jackets',
            level: 3,
            subcategories: [],
          },
          {
            id: 99,
            hierarchyId: 134,
            name: 'Maternity',
            slug: 'maternity',
            level: 3,
            subcategories: [],
          },
          {
            id: 100,
            hierarchyId: 135,
            name: 'Playsuits',
            slug: 'playsuits',
            level: 3,
            subcategories: [],
          },
          {
            id: 61,
            hierarchyId: 136,
            name: 'Socks',
            slug: 'socks',
            level: 3,
            subcategories: [],
          },
          {
            id: 63,
            hierarchyId: 137,
            name: 'T-Shirts',
            slug: 't-shirts',
            level: 3,
            subcategories: [
              {
                id: 71,
                hierarchyId: 139,
                name: 'Oversized',
                slug: 'oversized',
                level: 4,
                subcategories: [],
              },
            ],
          },
          {
            id: 101,
            hierarchyId: 138,
            name: 'Tops',
            slug: 'tops',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 7,
        hierarchyId: 12,
        name: 'Shoes',
        slug: 'shoes',
        level: 2,
        subcategories: [
          {
            id: 74,
            hierarchyId: 140,
            name: 'Sneakers',
            slug: 'sneakers',
            level: 3,
            subcategories: [],
          },
          {
            id: 70,
            hierarchyId: 141,
            name: 'Formal',
            slug: 'formal',
            level: 3,
            subcategories: [],
          },
          {
            id: 75,
            hierarchyId: 142,
            name: 'Slip-Ons',
            slug: 'slip-ons',
            level: 3,
            subcategories: [],
          },
          {
            id: 76,
            hierarchyId: 143,
            name: 'Boots',
            slug: 'boots',
            level: 3,
            subcategories: [],
          },
          {
            id: 77,
            hierarchyId: 144,
            name: 'Sandals',
            slug: 'sandals',
            level: 3,
            subcategories: [],
          },
          {
            id: 102,
            hierarchyId: 145,
            name: 'Heels',
            slug: 'heels',
            level: 3,
            subcategories: [],
          },
          {
            id: 103,
            hierarchyId: 146,
            name: 'Wedges',
            slug: 'wedges',
            level: 3,
            subcategories: [],
          },
          {
            id: 104,
            hierarchyId: 147,
            name: 'Flats',
            slug: 'flats',
            level: 3,
            subcategories: [],
          },
          {
            id: 105,
            hierarchyId: 148,
            name: 'Flip Flops',
            slug: 'flip-flops',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 8,
        hierarchyId: 13,
        name: 'Accessories',
        slug: 'accessories',
        level: 2,
        subcategories: [
          {
            id: 85,
            hierarchyId: 149,
            name: 'Watches',
            slug: 'watches',
            level: 3,
            subcategories: [],
          },
          {
            id: 86,
            hierarchyId: 150,
            name: 'Eyewear',
            slug: 'eyewear',
            level: 3,
            subcategories: [],
          },
          {
            id: 87,
            hierarchyId: 151,
            name: 'Jewellery',
            slug: 'jewellery',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 9,
        hierarchyId: 14,
        name: 'Bags',
        slug: 'bags',
        level: 2,
        subcategories: [
          {
            id: 88,
            hierarchyId: 152,
            name: 'Backpacks',
            slug: 'backpacks',
            level: 3,
            subcategories: [],
          },
          {
            id: 89,
            hierarchyId: 153,
            name: 'Travel Bags',
            slug: 'travel-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 90,
            hierarchyId: 154,
            name: 'Tote Bags',
            slug: 'tote-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 91,
            hierarchyId: 155,
            name: 'Laptop Bags',
            slug: 'laptop-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 92,
            hierarchyId: 156,
            name: 'Crossbody Bags',
            slug: 'crossbody-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 106,
            hierarchyId: 157,
            name: 'Handbags',
            slug: 'handbags',
            level: 3,
            subcategories: [],
          },
          {
            id: 107,
            hierarchyId: 158,
            name: 'Clutch Bags',
            slug: 'clutch-bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 108,
            hierarchyId: 159,
            name: 'Leather Bags',
            slug: 'leather-bags',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 4,
        hierarchyId: 15,
        name: 'Sports',
        slug: 'sports',
        level: 2,
        subcategories: [
          {
            id: 6,
            hierarchyId: 160,
            name: 'Clothing',
            slug: 'clothing',
            level: 3,
            subcategories: [],
          },
          {
            id: 7,
            hierarchyId: 161,
            name: 'Shoes',
            slug: 'shoes',
            level: 3,
            subcategories: [],
          },
          {
            id: 8,
            hierarchyId: 162,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 14,
        hierarchyId: 23,
        name: 'Beauty',
        slug: 'beauty',
        level: 2,
        subcategories: [
          {
            id: 18,
            hierarchyId: 163,
            name: 'Skin Care',
            slug: 'skin-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 109,
            hierarchyId: 164,
            name: 'Nail Care',
            slug: 'nail-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 20,
            hierarchyId: 165,
            name: 'Hair Care',
            slug: 'hair-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 93,
            hierarchyId: 166,
            name: 'Fragrance',
            slug: 'fragrance',
            level: 3,
            subcategories: [],
          },
          {
            id: 22,
            hierarchyId: 167,
            name: 'Bath and Body',
            slug: 'bath-and-body',
            level: 3,
            subcategories: [],
          },
          {
            id: 8,
            hierarchyId: 168,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 10,
        hierarchyId: 26,
        name: 'Localwears',
        slug: 'localwears',
        level: 2,
        subcategories: [],
      },
    ],
  },
  {
    id: 3,
    hierarchyId: 3,
    name: 'Kids',
    slug: 'kids',
    level: 1,
    subcategories: [
      {
        id: 6,
        hierarchyId: 16,
        name: 'Clothing',
        slug: 'clothing',
        level: 2,
        subcategories: [
          {
            id: 101,
            hierarchyId: 169,
            name: 'Tops',
            slug: 'tops',
            level: 3,
            subcategories: [],
          },
          {
            id: 54,
            hierarchyId: 170,
            name: 'Shorts',
            slug: 'shorts',
            level: 3,
            subcategories: [],
          },
          {
            id: 55,
            hierarchyId: 171,
            name: 'Underwear',
            slug: 'underwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 95,
            hierarchyId: 172,
            name: 'Skirts',
            slug: 'skirts',
            level: 3,
            subcategories: [],
          },
          {
            id: 110,
            hierarchyId: 173,
            name: 'Costumes',
            slug: 'costumes',
            level: 3,
            subcategories: [],
          },
          {
            id: 111,
            hierarchyId: 174,
            name: 'Clothing Sets',
            slug: 'clothing-sets',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 7,
        hierarchyId: 17,
        name: 'Shoes',
        slug: 'shoes',
        level: 2,
        subcategories: [
          {
            id: 76,
            hierarchyId: 175,
            name: 'Boots',
            slug: 'boots',
            level: 3,
            subcategories: [],
          },
          {
            id: 74,
            hierarchyId: 176,
            name: 'Sneakers',
            slug: 'sneakers',
            level: 3,
            subcategories: [],
          },
          {
            id: 77,
            hierarchyId: 177,
            name: 'Sandals',
            slug: 'sandals',
            level: 3,
            subcategories: [],
          },
          {
            id: 104,
            hierarchyId: 178,
            name: 'Flats',
            slug: 'flats',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 8,
        hierarchyId: 18,
        name: 'Accessories',
        slug: 'accessories',
        level: 2,
        subcategories: [
          {
            id: 112,
            hierarchyId: 179,
            name: 'Headwear',
            slug: 'headwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 113,
            hierarchyId: 180,
            name: 'Scarves and Gloves',
            slug: 'scarves-and-gloves',
            level: 3,
            subcategories: [],
          },
          {
            id: 114,
            hierarchyId: 181,
            name: 'Belt',
            slug: 'belt',
            level: 3,
            subcategories: [],
          },
          {
            id: 115,
            hierarchyId: 182,
            name: 'Towels',
            slug: 'towels',
            level: 3,
            subcategories: [],
          },
          {
            id: 88,
            hierarchyId: 183,
            name: 'Backpacks',
            slug: 'backpacks',
            level: 3,
            subcategories: [],
          },
          {
            id: 9,
            hierarchyId: 184,
            name: 'Bags',
            slug: 'bags',
            level: 3,
            subcategories: [],
          },
          {
            id: 116,
            hierarchyId: 185,
            name: 'Blankets',
            slug: 'blankets',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 4,
        hierarchyId: 19,
        name: 'Sports',
        slug: 'sports',
        level: 2,
        subcategories: [
          {
            id: 101,
            hierarchyId: 186,
            name: 'Tops',
            slug: 'tops',
            level: 3,
            subcategories: [],
          },
          {
            id: 117,
            hierarchyId: 187,
            name: 'Bottoms',
            slug: 'bottoms',
            level: 3,
            subcategories: [],
          },
          {
            id: 74,
            hierarchyId: 188,
            name: 'Sneakers',
            slug: 'sneakers',
            level: 3,
            subcategories: [],
          },
          {
            id: 8,
            hierarchyId: 189,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 11,
        hierarchyId: 20,
        name: 'Boys',
        slug: 'boys',
        level: 2,
        subcategories: [],
      },
      {
        id: 12,
        hierarchyId: 21,
        name: 'Girls',
        slug: 'girls',
        level: 2,
        subcategories: [],
      },
      {
        id: 13,
        hierarchyId: 22,
        name: 'Baby',
        slug: 'baby',
        level: 2,
        subcategories: [],
      },
    ],
  },
  {
    id: 4,
    hierarchyId: 4,
    name: 'Sports',
    slug: 'sports',
    level: 1,
    subcategories: [
      {
        id: 1,
        hierarchyId: 27,
        name: 'Men',
        slug: 'men',
        level: 2,
        subcategories: [
          {
            id: 6,
            hierarchyId: 204,
            name: 'Clothing',
            slug: 'clothing',
            level: 3,
            subcategories: [
              {
                id: 63,
                hierarchyId: 207,
                name: 'T-Shirts',
                slug: 't-shirts',
                level: 4,
                subcategories: [],
              },
              {
                id: 54,
                hierarchyId: 208,
                name: 'Shorts',
                slug: 'shorts',
                level: 4,
                subcategories: [],
              },
              {
                id: 64,
                hierarchyId: 209,
                name: 'Pants',
                slug: 'pants',
                level: 4,
                subcategories: [],
              },
              {
                id: 62,
                hierarchyId: 210,
                name: 'Outwears',
                slug: 'outwears',
                level: 4,
                subcategories: [],
              },
              {
                id: 98,
                hierarchyId: 211,
                name: 'Swimwear',
                slug: 'swimwear',
                level: 4,
                subcategories: [],
              },
              {
                id: 56,
                hierarchyId: 212,
                name: 'Beachwear',
                slug: 'beachwear',
                level: 4,
                subcategories: [],
              },
              {
                id: 118,
                hierarchyId: 213,
                name: 'Tanktops and Singlets',
                slug: 'tanktops-and-singlets',
                level: 4,
                subcategories: [],
              },
              {
                id: 52,
                hierarchyId: 214,
                name: 'Polos',
                slug: 'polos',
                level: 4,
                subcategories: [],
              },
            ],
          },
          {
            id: 119,
            hierarchyId: 205,
            name: 'Footwear',
            slug: 'footwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 8,
            hierarchyId: 206,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 2,
        hierarchyId: 28,
        name: 'Women',
        slug: 'women',
        level: 2,
        subcategories: [
          {
            id: 6,
            hierarchyId: 194,
            name: 'Clothing',
            slug: 'clothing',
            level: 3,
            subcategories: [
              {
                id: 63,
                hierarchyId: 195,
                name: 'T-Shirts',
                slug: 't-shirts',
                level: 4,
                subcategories: [],
              },
              {
                id: 54,
                hierarchyId: 196,
                name: 'Shorts',
                slug: 'shorts',
                level: 4,
                subcategories: [],
              },
              {
                id: 64,
                hierarchyId: 197,
                name: 'Pants',
                slug: 'pants',
                level: 4,
                subcategories: [],
              },
              {
                id: 62,
                hierarchyId: 198,
                name: 'Outwears',
                slug: 'outwears',
                level: 4,
                subcategories: [],
              },
              {
                id: 98,
                hierarchyId: 199,
                name: 'Swimwear',
                slug: 'swimwear',
                level: 4,
                subcategories: [],
              },
              {
                id: 56,
                hierarchyId: 200,
                name: 'Beachwear',
                slug: 'beachwear',
                level: 4,
                subcategories: [],
              },
              {
                id: 118,
                hierarchyId: 201,
                name: 'Tanktops and Singlets',
                slug: 'tanktops-and-singlets',
                level: 4,
                subcategories: [],
              },
            ],
          },
          {
            id: 119,
            hierarchyId: 202,
            name: 'Footwear',
            slug: 'footwear',
            level: 3,
            subcategories: [],
          },
          {
            id: 8,
            hierarchyId: 203,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 3,
        hierarchyId: 29,
        name: 'Kids',
        slug: 'kids',
        level: 2,
        subcategories: [
          {
            id: 74,
            hierarchyId: 190,
            name: 'Sneakers',
            slug: 'sneakers',
            level: 3,
            subcategories: [],
          },
          {
            id: 101,
            hierarchyId: 191,
            name: 'Tops',
            slug: 'tops',
            level: 3,
            subcategories: [],
          },
          {
            id: 117,
            hierarchyId: 192,
            name: 'Bottoms',
            slug: 'bottoms',
            level: 3,
            subcategories: [],
          },
          {
            id: 8,
            hierarchyId: 193,
            name: 'Accessories',
            slug: 'accessories',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 16,
        hierarchyId: 30,
        name: 'Brands',
        slug: 'brands',
        level: 2,
        subcategories: [],
      },
      {
        id: 17,
        hierarchyId: 31,
        name: 'Activities',
        slug: 'activities',
        level: 2,
        subcategories: [],
      },
    ],
  },
  {
    id: 5,
    hierarchyId: 5,
    name: 'Groomity',
    slug: 'groomity',
    level: 1,
    subcategories: [
      {
        id: 18,
        hierarchyId: 32,
        name: 'Skin Care',
        slug: 'skin-care',
        level: 2,
        subcategories: [
          {
            id: 23,
            hierarchyId: 39,
            name: 'Masks',
            slug: 'masks',
            level: 3,
            subcategories: [],
          },
          {
            id: 24,
            hierarchyId: 40,
            name: 'Moisturisers',
            slug: 'moisturisers',
            level: 3,
            subcategories: [],
          },
          {
            id: 25,
            hierarchyId: 41,
            name: 'Sun Care',
            slug: 'sun-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 26,
            hierarchyId: 42,
            name: 'Skincare Sets',
            slug: 'skincare-sets',
            level: 3,
            subcategories: [],
          },
          {
            id: 27,
            hierarchyId: 43,
            name: 'Cleansers',
            slug: 'cleansers',
            level: 3,
            subcategories: [],
          },
          {
            id: 28,
            hierarchyId: 44,
            name: 'Toners',
            slug: 'toners',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 19,
        hierarchyId: 33,
        name: 'Make Up',
        slug: 'make-up',
        level: 2,
        subcategories: [
          {
            id: 29,
            hierarchyId: 45,
            name: 'Cheeks',
            slug: 'cheeks',
            level: 3,
            subcategories: [],
          },
          {
            id: 30,
            hierarchyId: 46,
            name: 'Face',
            slug: 'face',
            level: 3,
            subcategories: [],
          },
          {
            id: 31,
            hierarchyId: 47,
            name: 'Lips',
            slug: 'lips',
            level: 3,
            subcategories: [],
          },
          {
            id: 32,
            hierarchyId: 48,
            name: 'Eyes',
            slug: 'eyes',
            level: 3,
            subcategories: [],
          },
          {
            id: 33,
            hierarchyId: 49,
            name: 'Removers',
            slug: 'removers',
            level: 3,
            subcategories: [],
          },
          {
            id: 34,
            hierarchyId: 50,
            name: 'Palettes',
            slug: 'palettes',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 20,
        hierarchyId: 34,
        name: 'Hair Care',
        slug: 'hair-care',
        level: 2,
        subcategories: [
          {
            id: 35,
            hierarchyId: 51,
            name: 'Shampooo and Conditioner',
            slug: 'shampooo-and-conditioner',
            level: 3,
            subcategories: [],
          },
          {
            id: 36,
            hierarchyId: 52,
            name: 'Hair Oils',
            slug: 'hair-oils',
            level: 3,
            subcategories: [],
          },
          {
            id: 37,
            hierarchyId: 53,
            name: 'Hair Tools',
            slug: 'hair-tools',
            level: 3,
            subcategories: [],
          },
          {
            id: 38,
            hierarchyId: 54,
            name: 'Hair Care Sets',
            slug: 'hair-care-sets',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 21,
        hierarchyId: 35,
        name: 'Fragrances',
        slug: 'fragrances',
        level: 2,
        subcategories: [
          {
            id: 39,
            hierarchyId: 55,
            name: 'Women Fragrances',
            slug: 'women-fragrances',
            level: 3,
            subcategories: [],
          },
          {
            id: 40,
            hierarchyId: 56,
            name: 'Men Fragrances',
            slug: 'men-fragrances',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 22,
        hierarchyId: 36,
        name: 'Bath and Body',
        slug: 'bath-and-body',
        level: 2,
        subcategories: [
          {
            id: 47,
            hierarchyId: 66,
            name: 'Personal Care',
            slug: 'personal-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 48,
            hierarchyId: 67,
            name: 'Hand and Body Wash',
            slug: 'hand-and-body-wash',
            level: 3,
            subcategories: [],
          },
          {
            id: 49,
            hierarchyId: 68,
            name: 'Scrubs and Exfoliants',
            slug: 'scrubs-and-exfoliants',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 15,
        hierarchyId: 37,
        name: "Men's Care",
        slug: 'men-care',
        level: 2,
        subcategories: [
          {
            id: 21,
            hierarchyId: 57,
            name: 'Fragrances',
            slug: 'fragrances',
            level: 3,
            subcategories: [],
          },
          {
            id: 18,
            hierarchyId: 58,
            name: 'Skin Care',
            slug: 'skin-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 20,
            hierarchyId: 59,
            name: 'Hair Care',
            slug: 'hair-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 41,
            hierarchyId: 60,
            name: 'Body Care',
            slug: 'body-care',
            level: 3,
            subcategories: [],
          },
          {
            id: 42,
            hierarchyId: 61,
            name: 'Grooming Tools',
            slug: 'grooming-tools',
            level: 3,
            subcategories: [],
          },
        ],
      },
      {
        id: 8,
        hierarchyId: 38,
        name: 'Accessories',
        slug: 'accessories',
        level: 2,
        subcategories: [
          {
            id: 43,
            hierarchyId: 62,
            name: 'Brushes and Blenders',
            slug: 'brushes-and-blenders',
            level: 3,
            subcategories: [],
          },
          {
            id: 44,
            hierarchyId: 63,
            name: 'Beauty Devices',
            slug: 'beauty-devices',
            level: 3,
            subcategories: [],
          },
          {
            id: 45,
            hierarchyId: 64,
            name: 'Beauty Accessories',
            slug: 'beauty-accessories',
            level: 3,
            subcategories: [],
          },
          {
            id: 46,
            hierarchyId: 65,
            name: 'Make Up Bags',
            slug: 'make-up-bags',
            level: 3,
            subcategories: [],
          },
        ],
      },
    ],
  },
];
